"""rom1.tool.clangd - the clangd language server (LSP over stdio).

    python3 -m rom1.tool.clangd            # probe: binary + compdb status
    python3 -m rom1.tool.clangd --index    # build the background index, wait

In-process (the rom1.lsp verbs and any other LSP consumer):
    from rom1.tool import clangd
    lsp = clangd.Clangd()                    # spawn + initialize
    try:
        lsp.open_file(path)
        lsp.references(path, line, char)     # 0-based positions throughout
    finally:
        lsp.close()

clangd is a READER of this MSVC5-dialect tree: it parses src/ against the
VC5/MFC/DX headers via build/clangd/compile_commands.json (generated by
rom1.graph.compdb; the committed .clangd adds the dialect flags). Its
diagnostics are NOT build truth - the wine `cl` build and objdiff are.

Cross-TU answers (workspace symbols, references into other TUs, rename
completeness) come from clangd's background index, built incrementally under
build/clangd/.cache/ on first use; `wait_for_index` blocks until it settles.
Per the layer rules this module only DRIVES the server and returns raw LSP
results; interpreting them (picking a symbol, applying a WorkspaceEdit) is
the caller's policy - see rom1/lsp/.
"""

from __future__ import annotations

import json
import os
import re
import select
import shutil
import subprocess
import sys
import time
from pathlib import Path

from rom1.core.paths import BUILD, REPO
from rom1.tool import ToolError

CDB_DIR = BUILD / "clangd"
CDB = CDB_DIR / "compile_commands.json"

_CONTENT_LENGTH = re.compile(rb"Content-Length: (\d+)")


def available() -> str | None:
    """Absolute path of the clangd binary, or None (NixOS shim caveat: the
    dev-shell clangd can vanish on a plugin bump - callers must cope)."""
    return shutil.which("clangd")


def first_compdb_file() -> Path:
    """The compdb's first entry - opening it kicks clangd's lazy CDB
    discovery and thus background indexing."""
    entry = json.loads(CDB.read_text())[0]
    p = Path(entry["file"])
    if not p.is_absolute():
        p = Path(entry.get("directory", REPO)) / p
    return p


class Clangd:
    """One clangd session over stdio (Content-Length framed JSON-RPC)."""

    def __init__(self, background_index: bool = True):
        if available() is None:
            raise ToolError("clangd is not on PATH - run inside `nix develop` "
                            "(the NixOS LSP shim also breaks on plugin bumps)")
        if not CDB.is_file():
            raise ToolError(f"{CDB.relative_to(REPO)} not found - run "
                            f"`python3 -m rom1.graph.compdb` (or a build)")
        self.proc = subprocess.Popen(
            ["clangd", f"--background-index={'true' if background_index else 'false'}",
             "--log=error",
             "--header-insertion=never",   # never let rename smuggle an #include
             "--rename-file-limit=0",
             f"--compile-commands-dir={CDB_DIR}"],
            cwd=REPO, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL)
        self._id = 0
        self._open_uris: set[str] = set()
        self._request("initialize", {
            "processId": os.getpid(), "rootUri": REPO.as_uri(),
            "capabilities": {
                # workDoneProgress lets clangd report background-index progress
                "window": {"workDoneProgress": True},
                # advertise documentChanges so rename may return either
                # WorkspaceEdit shape (the caller normalizes both)
                "workspace": {"workspaceEdit": {"documentChanges": True}},
                "textDocument": {
                    "rename": {"prepareSupport": True},
                    # hierarchical DocumentSymbol[] (full body ranges) rather
                    # than the flat, header-leaking SymbolInformation[]
                    "documentSymbol": {
                        "hierarchicalDocumentSymbolSupport": True},
                },
            }})
        self._notify("initialized", {})

    # --- framing ----------------------------------------------------------- #
    def _send(self, payload: dict) -> None:
        body = json.dumps({"jsonrpc": "2.0", **payload}).encode()
        self.proc.stdin.write(f"Content-Length: {len(body)}\r\n\r\n".encode()
                              + body)
        self.proc.stdin.flush()

    def _recv(self) -> dict:
        headers = b""
        while not headers.endswith(b"\r\n\r\n"):
            b1 = self.proc.stdout.read(1)
            if not b1:      # EOF: clangd died - without this the loop spins
                raise ToolError("clangd exited unexpectedly (EOF on stdout)")
            headers += b1
        length = int(_CONTENT_LENGTH.search(headers).group(1))
        return json.loads(self.proc.stdout.read(length))

    def _notify(self, method: str, params: dict) -> None:
        self._send({"method": method, "params": params})

    def _request(self, method: str, params: dict, timeout: float = 120.0,
                 tolerant: bool = False):
        """`tolerant` returns None on a clangd error instead of raising - used
        when probing positions that may not hold a symbol (a comment token)."""
        self._id += 1
        self._send({"id": self._id, "method": method, "params": params})
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            msg = self._recv()
            # clangd may interleave a progress-token create request
            if msg.get("method") == "window/workDoneProgress/create":
                self._send({"id": msg["id"], "result": None})
                continue
            if msg.get("id") == self._id:
                if "error" in msg:
                    if tolerant:
                        return None
                    raise ToolError(
                        f"clangd error ({method}): {msg['error'].get('message')}")
                return msg.get("result")
        raise ToolError(f"clangd: no reply to {method} within {timeout}s")

    # --- lifecycle --------------------------------------------------------- #
    def wait_for_index(self, stream=None) -> None:
        """Block until background indexing reports 'end' (or stays idle).
        Progress goes to `stream` (default stderr, keeping result listings on
        stdout clean). Pre-begin, clangd quietly validates existing shards -
        a warm cache can idle a while before the first message."""
        stream = stream or sys.stderr
        begun = False
        last = time.monotonic()
        while True:
            ready, _, _ = select.select([self.proc.stdout], [], [], 5.0)
            if not ready:
                if time.monotonic() - last > (30.0 if begun else 90.0):
                    print("index: idle - nothing (left) to index" if not begun
                          else "\nindex: no progress for 30s - assuming done",
                          file=stream)
                    return
                continue
            msg = self._recv()
            last = time.monotonic()
            if msg.get("method") == "window/workDoneProgress/create":
                self._send({"id": msg["id"], "result": None})
                continue
            if msg.get("method") != "$/progress":
                continue
            value = msg["params"]["value"]
            if value.get("kind") == "begin":
                begun = True
            elif value.get("kind") == "report":
                pct = value.get("percentage")
                txt = value.get("message", "")
                print(f"\rindex: {pct}% {txt[:60]:<60}", end="", flush=True,
                      file=stream)
            elif value.get("kind") == "end" and begun:
                print("\nindex: done", file=stream)
                return

    def close(self) -> None:
        try:
            self._request("shutdown", {}, timeout=5)
            self._notify("exit", {})
        except (ToolError, OSError):    # best-effort teardown of a one-shot
            pass
        self.proc.terminate()

    # --- verbs (raw LSP results; positions 0-based) ------------------------ #
    def open_file(self, path: Path) -> None:
        """Idempotent didOpen (a second didOpen of an open document is a
        protocol violation). Opening any compdb-listed file also kicks
        clangd's lazy CDB discovery, which is what loads the index shards."""
        uri = path.as_uri()
        if uri in self._open_uris:
            return
        self._open_uris.add(uri)
        self._notify("textDocument/didOpen", {"textDocument": {
            "uri": uri, "languageId": "cpp", "version": 1,
            "text": path.read_text(errors="replace")}})

    def workspace_symbols(self, query: str) -> list:
        return self._request("workspace/symbol", {"query": query}) or []

    def document_symbols(self, path: Path) -> list:
        self.open_file(path)
        return self._request("textDocument/documentSymbol", {
            "textDocument": {"uri": path.as_uri()}}) or []

    def references(self, path: Path, line: int, char: int) -> list:
        return self._request("textDocument/references", {
            "textDocument": {"uri": path.as_uri()},
            "position": {"line": line, "character": char},
            "context": {"includeDeclaration": True}}, tolerant=True) or []

    def hover(self, path: Path, line: int, char: int):
        return self._request("textDocument/hover", {
            "textDocument": {"uri": path.as_uri()},
            "position": {"line": line, "character": char}}, tolerant=True)

    def rename(self, path: Path, line: int, char: int, new_name: str):
        """WorkspaceEdit (decl + every reference, keyed on the symbol's USR)
        or None on a non-symbol position."""
        return self._request("textDocument/rename", {
            "textDocument": {"uri": path.as_uri()},
            "position": {"line": line, "character": char},
            "newName": new_name}, tolerant=True)


def clang_query(matcher: str, files: list[str], timeout: float = 600.0) -> str:
    """clang-query's stdout for one AST matcher over `files` (repo-relative),
    against the same compdb. The rename audit's engine."""
    if shutil.which("clang-query") is None:
        raise ToolError("clang-query is not on PATH (need `nix develop`)")
    proc = subprocess.run(
        ["clang-query", "-p", str(CDB_DIR), "-c", matcher, *files, "--"],
        cwd=REPO, capture_output=True, text=True, timeout=timeout)
    return proc.stdout


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--index", action="store_true",
                    help="build the background index and wait until it settles")
    a = ap.parse_args()
    exe = available()
    if exe is None:
        print("[clangd] NOT on PATH - run inside `nix develop`", file=sys.stderr)
        return 1
    version = subprocess.run(["clangd", "--version"], capture_output=True,
                             text=True).stdout.splitlines()[0]
    print(f"[clangd] {exe} ({version})")
    if not CDB.is_file():
        print(f"[clangd] compdb MISSING at {CDB.relative_to(REPO)} - run "
              f"`python3 -m rom1.graph.compdb`", file=sys.stderr)
        return 1
    print(f"[clangd] compdb {CDB.relative_to(REPO)} "
          f"({len(json.loads(CDB.read_text()))} units)")
    if a.index:
        lsp = Clangd()
        try:
            lsp.open_file(first_compdb_file())
            lsp.wait_for_index()
        finally:
            lsp.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
