"""rom1.verify.baseline - config/match_baseline.tsv I/O.

The schema is the ported one, byte-compatible for its other reader
(rom1.walls.inventory reads cols[2] best_pct, cols[5] src_hash, cols[6] rva
on rows with >= 7 columns). One column is APPENDED (never inserted): `state`,
empty for a scored row, `absent` for a row bank preserved while its body was
not scored (the high-water kept for a later natural emitter). Old-format rows
without it parse as scored.
"""

from __future__ import annotations

import sys

from rom1.core.paths import CONFIG

BASELINE = CONFIG / "match_baseline.tsv"

EPS = 0.01      # ignore sub-0.01% jitter
LEDGER_DP = 4   # the file stores percentages to this many decimals


def at_ledger_precision(pct: float) -> float:
    """A live score rounded to how the ledger STORES it.

    Every below-best test must use this: `cur_pct` comes back from the file
    already rounded, so comparing a raw float on one side and a stored value
    on the other makes a row whose dip is exactly EPS both regressed (raw)
    and never-carried (stored) - permanently `fresh`, an unclearable gate.
    """
    return round(pct, LEDGER_DP)


def below_best(pct: float, best: float) -> bool:
    """THE below-best predicate - every caller must use this one.

    Regress classification, the carried/fresh split and the gate all have to
    agree; when they disagreed at the rounding boundary a row could be
    regressed AND never-carried at once, i.e. an unclearable gate.
    """
    return at_ledger_precision(pct) < best - EPS


EXACT = 99.995  # objdiff scores a byte-exact function at 100% (float slop)

HEADER = (
    "# rom1 match baseline - generated by rom1.verify. DO NOT hand-edit.\n"
    "#   units rows:     unit  n_functions  matched   (matched = at 100% fuzzy now;\n"
    "#                    the README's per-module 'exact' uses objdiff's byte-exact count)\n"
    "#   function rows:  unit  function  best_pct  cur_pct  tries  src_hash  rva  hist_pct  state\n"
    "#   rva      = retail RVA (stable identity): a vanished row whose rva is still\n"
    "#              occupied is a rename, not a loss - so signature edits don't regress.\n"
    "#              It is ALSO what gates best_pct: the rva identifies the BODY, and a\n"
    "#              best measures a body, not a name (see verify.classify.rebound()).\n"
    "#   best_pct = best this IMPLEMENTATION has scored - the REGRESSION gate. Same\n"
    "#              src_hash + a different %% means TU composition moved, so the high\n"
    "#              mark is banked; a CHANGED src_hash resets it to cur (the old peak\n"
    "#              belonged to different source). best == 100 means ALREADY FIXED.\n"
    "#   hist_pct = the all-time peak any implementation reached; NEVER resets. Its job\n"
    "#              is the opposite: hist > best means KNOWN HEADROOM, i.e. we had a\n"
    "#              better implementation once and lost it - a worklist row.\n"
    "#              A RATCHET: for a given rva it never decreases; only the rva MOVING\n"
    "#              (the name now labels a different body) may lower it. Editing a\n"
    "#              function does NOT - that is exactly when the high-water must hold\n"
    "#              (structure over current %).\n"
    "#   cur_pct  = fuzzy% at THIS bank - diff the file across commits to see the moves\n"
    "#              while best_pct holds.\n"
    "#   tries    = times this function's source fingerprint changed (how much it has\n"
    "#              been worked on - high = hard to match).\n"
    "#   src_hash = per-function source fingerprint. Drives tries + the TOUCHED/REGRESS\n"
    "#              split and the best-reset on a real edit; a `cpp:` prefix marks the\n"
    "#              whole-.cpp fallback (unknown, never counted as an edit).\n"
    "#   state    = '' scored at the last bank | 'absent' preserved while unscored\n"
    "#              (no natural emitter in that build; the MAX is kept so a later\n"
    "#              emitter resumes from it instead of forgetting proven work).\n"
    "# Query: python3 -m rom1.verify status | check | bank\n"
)


def unit_counts(funcs: dict[tuple[str, str], dict]) -> dict[str, dict]:
    """Per-unit {n: total functions, matched: functions at 100% now}."""
    out: dict[str, dict] = {}
    for (unit, _), f in funcs.items():
        a = out.setdefault(unit, {"n": 0, "matched": 0})
        a["n"] += 1
        if f["cur"] >= EXACT:
            a["matched"] += 1
    return out


def load(text: str | None = None) -> dict[tuple[str, str], dict]:
    """Parse the [functions] section into
    {(unit, fn): {best, cur, tries, fp, addr, hist, state}}.

    The [units] counts are derived (unit_counts), so they are skipped here.
    `text` overrides the on-disk file (tests / `git show` output).
    """
    funcs: dict[tuple[str, str], dict] = {}
    if text is None:
        if not BASELINE.is_file():
            return funcs
        text = BASELINE.read_text()
    section = None
    bad = 0
    for line in text.splitlines():
        if line.startswith("# [units]\t"):    # tab-precise: not the HEADER prose
            section = "units"
            continue
        if line.startswith("# [functions]\t"):
            section = "functions"
            continue
        if not line or line.startswith("#") or section != "functions":
            continue
        c = line.split("\t")
        try:
            if len(c) < 6:
                raise ValueError("too few columns")
            addr = int(c[6], 16) if len(c) > 6 and c[6] else None
            hist = float(c[7]) if len(c) > 7 and c[7] else float(c[2])
            state = c[8] if len(c) > 8 else ""
            funcs[(c[0], c[1])] = {
                "best": float(c[2]), "cur": float(c[3]), "tries": int(c[4]),
                "fp": c[5], "addr": addr, "hist": hist, "state": state}
        except ValueError:
            bad += 1
    if bad:
        print(f"warning: {bad} malformed/old-format baseline row(s) skipped",
              file=sys.stderr)
    return funcs


def render(funcs: dict[tuple[str, str], dict]) -> str:
    units = unit_counts(funcs)
    lines = [HEADER, "# [units]\tunit\tn_functions\tmatched\n"]
    for unit in sorted(units):
        u = units[unit]
        lines.append(f"{unit}\t{u['n']}\t{u['matched']}\n")
    lines.append("# [functions]\tunit\tfunction\tbest_pct\tcur_pct\ttries"
                 "\tsrc_hash\trva\thist_pct\tstate\n")
    for key in sorted(funcs):
        unit, fn = key
        f = funcs[key]
        addr = f.get("addr")
        line = (f"{unit}\t{fn}\t{f['best']:.4f}\t{f['cur']:.4f}\t{f['tries']}"
                f"\t{f['fp']}")
        line += f"\t0x{addr:x}" if addr is not None else "\t"
        line += f"\t{f.get('hist', f['best']):.4f}\t{f.get('state', '')}"
        lines.append(line + "\n")
    return "".join(lines)


def write(funcs: dict[tuple[str, str], dict]) -> bool:
    """Write the baseline; True when the file actually changed."""
    text = render(funcs)
    if BASELINE.is_file() and BASELINE.read_text() == text:
        return False
    BASELINE.write_text(text)
    return True
