"""rom1.verify.fingerprints - per-function source fingerprints (src_hash).

The ported mechanism: a function's src_hash is the 12-hex sha1 of ITS OWN
source extent, recovered by asking clangd for the unit's hierarchical
documentSymbol tree and hashing the body range(s) of the matching qualified
name. Hashing a whole .cpp is too coarse - editing one function would reset
the high-water of every sibling in the unit, hiding collateral regressions.

Bridge from the report's MANGLED names to clangd's source-level names:
  * C++ (?...):  llvm-undname -> "Class::Method" -> clangd qualified symbol.
  * C   (_name): strip the cdecl/stdcall decoration (leading `_`, trailing
                 `@N`) -> clangd source name.
A function clangd cannot resolve gets NO entry, and the fingerprinter falls
back to the unit's whole-.cpp hash, tagged `cpp:` = "no per-function
fingerprint available". A fallback is UNKNOWN and must never count as an
edit (else a stale cache hides regressions and corrupts the baseline).

The cache is DERIVED, incremental (only units whose .cpp hash moved get
re-parsed), and lives in build/gen/ (this slice's scratch). The old
pipeline's cache at build/clangd/func_fingerprints.tsv is read as a SEED
when the new one is absent - same format, same hash domain - so banked
src_hash provenance carries over without a full re-parse.
"""

from __future__ import annotations

import hashlib
import re
import subprocess
from pathlib import Path

from rom1.core.paths import BUILD, REPO

CACHE = BUILD / "gen/func_fingerprints.tsv"
SEED = BUILD / "clangd/func_fingerprints.tsv"   # old pipeline's cache (read-only)
CDB_DIR = BUILD / "clangd"                       # compile_commands.json home

FALLBACK = "cpp:"  # marks a fingerprint we could NOT resolve per-function


def is_fallback(h: str) -> bool:
    return h.startswith(FALLBACK)


def real_edit(prev_fp: str, cur_fp: str) -> bool:
    """True only when BOTH sides are real (non-fallback) fingerprints that
    differ - a genuine source edit, not a cache hash-domain change."""
    return not is_fallback(prev_fp) and not is_fallback(cur_fp) \
        and prev_fp != cur_fp


def cpp_hash(source: str) -> str:
    """12-hex sha1 of a unit's whole source file (the unit-level fallback)."""
    p = REPO / source
    return hashlib.sha1(p.read_bytes()).hexdigest()[:12] if p.is_file() \
        else "nosrc"


def _sha12(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()[:12]


def unit_sources() -> dict[str, str]:
    from rom1 import manifest
    return {u["unit"]: u.get("source", "") for u in manifest.units()}


def unit_mangled() -> dict[str, set]:
    """unit -> {mangled names}, from the Model (the one rva/unit/name join)."""
    from rom1.model import resolve
    out: dict[str, set] = {}
    for b in resolve().functions:
        if b.name and b.unit:
            out.setdefault(b.unit, set()).add(b.name)
    return out


# --------------------------------------------------------------------------- #
# cache I/O                                                                   #
# --------------------------------------------------------------------------- #
def load_cache() -> tuple[dict[str, dict], dict[tuple[str, str], str]]:
    """(units{unit: {cpp_hash, source}}, funcs{(unit, mangled): src_hash})."""
    units: dict[str, dict] = {}
    funcs: dict[tuple[str, str], str] = {}
    path = CACHE if CACHE.is_file() else SEED
    if not path.is_file():
        return units, funcs
    section = None
    for line in path.read_text().splitlines():
        if line.startswith("# [units]"):
            section = "u"
            continue
        if line.startswith("# [functions]"):
            section = "f"
            continue
        if not line or line.startswith("#"):
            continue
        c = line.split("\t")
        if section == "u" and len(c) >= 3:
            units[c[0]] = {"cpp_hash": c[1], "source": c[2]}
        elif section == "f" and len(c) >= 3:
            funcs[(c[0], c[1])] = c[2]
    return units, funcs


def write_cache(units: dict[str, dict],
                funcs: dict[tuple[str, str], str]) -> None:
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    out = ["# func source fingerprints - generated by rom1.verify."
           "fingerprints.\n",
           "# Derived cache (gitignored). Consumed by rom1.verify.\n",
           "# [units]\tunit\tcpp_hash\tsource\n"]
    for u in sorted(units):
        out.append(f"{u}\t{units[u]['cpp_hash']}\t{units[u]['source']}\n")
    out.append("# [functions]\tunit\tmangled\tsrc_hash\n")
    for k in sorted(funcs):
        out.append(f"{k[0]}\t{k[1]}\t{funcs[k]}\n")
    CACHE.write_text("".join(out))


# --------------------------------------------------------------------------- #
# the fingerprinter (what bank/check consume)                                 #
# --------------------------------------------------------------------------- #
def fingerprinter():
    """Return (fp, cpp_of, stale): fp(unit, mangled) -> CURRENT fingerprint.

    The cache's per-function range hash when the cache is fresh for the unit
    AND has the function; otherwise a FALLBACK-tagged whole-.cpp hash. `stale`
    collects units whose cache is stale/absent (the dangerous fallback).
    """
    sources = unit_sources()
    cache_units, cache_funcs = load_cache()
    cur_cpp: dict[str, str] = {}

    def cpp_of(unit: str) -> str:
        if unit not in cur_cpp:
            cur_cpp[unit] = cpp_hash(sources.get(unit, ""))
        return cur_cpp[unit]

    stale: set = set()

    def fp(unit: str, mangled: str) -> str:
        h = cpp_of(unit)
        cu = cache_units.get(unit)
        if cu and cu.get("cpp_hash") == h:
            real = cache_funcs.get((unit, mangled))
            if real is not None:
                return real                     # real per-function range hash
            return FALLBACK + h                 # fresh unit, fn unmappable
        stale.add(unit)                         # unit's cache stale/absent
        return FALLBACK + h

    return fp, cpp_of, stale


# --------------------------------------------------------------------------- #
# mangled -> qualified source name bridge                                     #
# --------------------------------------------------------------------------- #
def demangle_map(names: set) -> dict[str, str]:
    """C++ mangled -> 'Class::Method' qualified key, one batched llvm-undname."""
    cpp = sorted(n for n in names if n.startswith("?"))
    if not cpp:
        return {}
    # NOTE the trailing newline: without it llvm-undname drops the final name.
    proc = subprocess.run(["llvm-undname"], input="\n".join(cpp) + "\n",
                          capture_output=True, text=True)
    out: dict[str, str] = {}
    for block in proc.stdout.split("\n\n"):
        lines = block.splitlines()
        if len(lines) >= 2 and lines[0] in names:
            q = _qualified_of(lines[1])
            if q:
                out[lines[0]] = q
    return out


def _qualified_of(demangled: str) -> str | None:
    """'public: int __thiscall CFileIO::Open(char const *,...)' -> 'CFileIO::Open'."""
    # A function-pointer return type wraps the declared name in parentheses:
    #   void (__cdecl * __thiscall C::Get(...))(char *, int)
    # The first `(` therefore belongs to the return type, not the parameter
    # list.  Prefer the qualified identifier which is itself followed by `(`.
    wrapped = re.search(
        r"(?<![\w:])((?:~?[A-Za-z_]\w*::)+~?[A-Za-z_]\w*)\s*\(",
        demangled)
    if wrapped:
        return wrapped.group(1)
    head = demangled.split("(", 1)[0].strip()    # drop the parameter list
    if not head:
        return None
    tok = head.split()[-1]                       # name follows retty/callconv
    if "`" in tok or "'" in tok:                 # compiler-generated -> no source
        return None
    return tok


def _candidates(mangled: str) -> list:
    """Source-name candidates for a C symbol: undo the cdecl/stdcall
    decoration (leading `_`, trailing `@N` stdcall arg-byte count)."""
    cands = []
    for n in (mangled, mangled.split("@", 1)[0]):
        cands += [n, n[1:] if n.startswith("_") else n, n.lstrip("_")]
    return list(dict.fromkeys(cands))


# --------------------------------------------------------------------------- #
# minimal clangd LSP client (documentSymbol only)                             #
# --------------------------------------------------------------------------- #
class Clangd:
    def __init__(self):
        import os
        self.proc = subprocess.Popen(
            ["clangd", "--log=error", "--header-insertion=never",
             "--background-index=false",
             f"--compile-commands-dir={CDB_DIR}"],
            cwd=REPO, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL)
        self._id = 0
        self._request("initialize", {
            "processId": os.getpid(), "rootUri": REPO.as_uri(),
            "capabilities": {"textDocument": {"documentSymbol": {
                "hierarchicalDocumentSymbolSupport": True}}}})
        self._notify("initialized", {})

    def _send(self, payload: dict) -> None:
        import json
        body = json.dumps({"jsonrpc": "2.0", **payload}).encode()
        self.proc.stdin.write(
            f"Content-Length: {len(body)}\r\n\r\n".encode() + body)
        self.proc.stdin.flush()

    def _recv(self) -> dict:
        import json
        import re
        headers = b""
        while not headers.endswith(b"\r\n\r\n"):
            b1 = self.proc.stdout.read(1)
            if not b1:
                raise RuntimeError("clangd exited unexpectedly (EOF)")
            headers += b1
        length = int(re.search(rb"Content-Length: (\d+)", headers).group(1))
        return json.loads(self.proc.stdout.read(length))

    def _notify(self, method: str, params: dict) -> None:
        self._send({"method": method, "params": params})

    def _request(self, method: str, params: dict, timeout: float = 120.0):
        import time
        self._id += 1
        self._send({"id": self._id, "method": method, "params": params})
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            msg = self._recv()
            if msg.get("method") == "window/workDoneProgress/create":
                self._send({"id": msg["id"], "result": None})
                continue
            if msg.get("id") == self._id:
                if "error" in msg:
                    raise RuntimeError(
                        f"clangd error: {msg['error'].get('message')}")
                return msg.get("result")
        raise RuntimeError(f"clangd: no reply to {method} within {timeout}s")

    def document_symbols(self, path: Path) -> list:
        self._notify("textDocument/didOpen", {"textDocument": {
            "uri": path.as_uri(), "languageId": "cpp", "version": 1,
            "text": path.read_text(errors="replace")}})
        return self._request("textDocument/documentSymbol", {
            "textDocument": {"uri": path.as_uri()}}) or []

    def close(self) -> None:
        try:
            self._request("shutdown", {}, timeout=5)
            self._notify("exit", {})
        except Exception:  # noqa: BLE001 - best-effort teardown
            pass
        self.proc.terminate()


def body_ranges(symbols: list) -> dict[str, list]:
    """Hierarchical DocumentSymbol[] -> {qualified_name: [(start, end)]}.

    Keep the multi-line range(s) (the definition body); a name with only
    single-line ranges keeps those. Genuine overloads are unioned.
    """
    acc: dict[str, list] = {}

    def walk(syms, prefix):
        for s in syms:
            k = s.get("kind")
            nm = s.get("name", "")
            if k in (6, 9, 12):  # Method / Constructor / Function
                r = s["range"]
                acc.setdefault(prefix + nm, []).append(
                    (r["start"]["line"], r["end"]["line"]))
            child_prefix = prefix + nm + "::" if k in (3, 5, 11, 23) else prefix
            walk(s.get("children") or [], child_prefix)

    walk(symbols, "")
    chosen: dict[str, list] = {}
    for name, ranges in acc.items():
        multi = [r for r in ranges if r[1] > r[0]]
        chosen[name] = sorted(multi or ranges)
    return chosen


def _hash_ranges(lines: list, ranges: list) -> str:
    chunks = ["\n".join(lines[a:b + 1]) for (a, b) in ranges]
    return _sha12("\n--\n".join(chunks))


# --------------------------------------------------------------------------- #
# regenerate (incremental)                                                    #
# --------------------------------------------------------------------------- #
def regenerate(force_all: bool = False, verbose: bool = False) -> int:
    sources = unit_sources()
    umang = unit_mangled()
    cache_units, cache_funcs = load_cache()

    cur_cpp: dict[str, str] = {}
    todo: list[str] = []
    for unit, source in sources.items():
        if not source:
            continue
        cur_cpp[unit] = cpp_hash(source)
        if force_all or cache_units.get(unit, {}).get("cpp_hash") != cur_cpp[unit]:
            todo.append(unit)

    new_units: dict[str, dict] = {}
    new_funcs: dict[tuple[str, str], str] = {}
    for unit, source in sources.items():           # carry unchanged units over
        if unit not in cur_cpp or unit in todo:
            continue
        new_units[unit] = {"cpp_hash": cur_cpp[unit], "source": source}
        for k, v in cache_funcs.items():
            if k[0] == unit:
                new_funcs[k] = v

    if todo:
        for unit in todo:
            new_units[unit] = {"cpp_hash": cur_cpp[unit],
                               "source": sources[unit]}
        allm: set = set()
        for u in todo:
            allm |= umang.get(u, set())
        if allm:
            m2q = demangle_map(allm)
            lsp = Clangd()
            try:
                for unit in todo:
                    path = (REPO / sources[unit]).resolve()
                    if not path.is_file():
                        continue
                    chosen = body_ranges(lsp.document_symbols(path))
                    lines = path.read_text(errors="replace").splitlines()
                    qhash = {q: _hash_ranges(lines, rs)
                             for q, rs in chosen.items()}
                    n = 0
                    for m in umang.get(unit, set()):
                        q = m2q.get(m) if m.startswith("?") else next(
                            (c for c in _candidates(m) if c in qhash), None)
                        if q and q in qhash:
                            new_funcs[(unit, m)] = qhash[q]
                            n += 1
                    if verbose:
                        print(f"  {unit}: {n}/{len(umang.get(unit, set()))} "
                              f"fingerprinted ({len(chosen)} defs in clangd)")
            finally:
                lsp.close()

    write_cache(new_units, new_funcs)
    print(f"func fingerprints: {len(new_funcs)} functions  "
          f"({len(todo)} unit(s) re-parsed, {len(new_units) - len(todo)} cached)")
    return 0


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(
        prog="rom1 verify fingerprints", description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--all", action="store_true",
                    help="re-parse every unit (ignore the cache)")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="name each unit as it is re-parsed")
    a = ap.parse_args(argv)
    return regenerate(force_all=a.all, verbose=a.verbose)
