"""Personal, source-hash-scoped review state for the Codex wall campaign.

This ledger does not inherit or validate ``@early-stop``.  A row means Codex
personally inspected that exact function implementation.  ``exact`` records a
100% result; ``bounded`` records an exhaustive attempt whose remaining residue
has no current evidence-backed source lever.  Both remove the row from
``rom1 walls inventory --todo``.  ``open`` keeps it in the queue and records
the next evidence-bearing action.  Any source edit changes the function
fingerprint and automatically makes the review stale.

    rom1 walls review <rva|name> --status open|bounded|exact
        --class referent|inline|cfg|regalloc|masked|other --evidence TEXT
    rom1 walls review --list
"""

from __future__ import annotations

from rom1.core.paths import REPO

REVIEWS = REPO / "config/codex_wall_reviews.tsv"
HEADER = (
    "# Codex wall reviews - generated by `rom1 walls review`; do not hand-edit.\n"
    "# rva\tsrc_hash\tstatus\twall_class\tevidence\n"
)
STATUSES = ("open", "bounded", "exact")
TERMINAL_STATUSES = frozenset(("bounded", "exact"))
CLASSES = ("referent", "inline", "cfg", "regalloc", "masked", "other")


def load() -> dict[int, dict[str, str]]:
    rows: dict[int, dict[str, str]] = {}
    if not REVIEWS.is_file():
        return rows
    for line in REVIEWS.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        cols = line.split("\t", 4)
        if len(cols) != 5:
            continue
        try:
            rva = int(cols[0], 16)
        except ValueError:
            continue
        rows[rva] = {
            "src_hash": cols[1],
            "status": cols[2],
            "wall_class": cols[3],
            "evidence": cols[4],
        }
    return rows


def render(rows: dict[int, dict[str, str]]) -> str:
    lines = [HEADER]
    for rva, row in sorted(rows.items()):
        evidence = row["evidence"].replace("\t", " ").replace("\n", " ")
        lines.append(
            f"0x{rva:06x}\t{row['src_hash']}\t{row['status']}\t"
            f"{row['wall_class']}\t{evidence}\n"
        )
    return "".join(lines)


def current() -> dict[int, dict[str, str]]:
    """Reviews whose recorded fingerprint matches the current source body."""
    from rom1.model import resolve
    from rom1.verify.fingerprints import fingerprinter

    fingerprint, _cpp_of, _stale = fingerprinter()
    fingerprints = {
        binding.rva: fingerprint(binding.unit, binding.name)
        for binding in resolve().functions
        if binding.name and binding.unit
    }
    return {
        rva: row for rva, row in load().items()
        if fingerprints.get(rva) == row["src_hash"]
    }


def exact_is_banked(rva: int, src_hash: str) -> bool:
    """Whether this exact source fingerprint has a 100% MAX bank."""
    from rom1.walls.inventory import baseline_rows

    bank = baseline_rows().get(rva)
    return bool(bank and bank[0] == 100.0 and bank[2] == src_hash)


def main(argv=None) -> int:
    import argparse

    ap = argparse.ArgumentParser(
        prog="rom1 walls review",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("target", nargs="?", help="hex RVA, mangled name, or CClass::Member")
    ap.add_argument("--status", choices=STATUSES)
    ap.add_argument("--class", dest="wall_class", choices=CLASSES)
    ap.add_argument("--evidence", help="concise proof or next evidence-bearing action")
    ap.add_argument("--list", action="store_true", help="show current and stale reviews")
    a = ap.parse_args(argv)

    rows = load()
    if a.list:
        live = current()
        print(f"[reviews] {len(live)} current, {len(rows) - len(live)} stale")
        for rva, row in sorted(rows.items()):
            freshness = "current" if rva in live else "STALE"
            print(
                f"  0x{rva:06x} {freshness:7} {row['status']:6} "
                f"{row['wall_class']:8} {row['evidence']}"
            )
        return 0

    if not a.target or not a.status or not a.wall_class or not a.evidence:
        ap.error("recording a review requires target, --status, --class, and --evidence")

    from rom1.walls.diagnose import _locate
    from rom1.verify.fingerprints import fingerprinter, is_fallback

    binding, why = _locate(a.target)
    if binding is None:
        ap.error(why)
    fingerprint, _cpp_of, _stale = fingerprinter()
    src_hash = fingerprint(binding.unit, binding.name)
    if is_fallback(src_hash):
        ap.error(
            f"0x{binding.rva:06x} has no fresh per-function source fingerprint; "
            "run `rom1 build` first"
        )
    if a.status == "exact" and not exact_is_banked(binding.rva, src_hash):
        ap.error(
            f"0x{binding.rva:06x} source {src_hash} has no banked 100% MAX; "
            "use --status bounded or run a full build while exact"
        )
    rows[binding.rva] = {
        "src_hash": src_hash,
        "status": a.status,
        "wall_class": a.wall_class,
        "evidence": a.evidence,
    }
    REVIEWS.write_text(render(rows))
    print(
        f"[reviews] 0x{binding.rva:06x} {a.status} {a.wall_class} "
        f"at {src_hash}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
