"""rom1.graph.play - the generated game runner (play.sh).

ONE definition of how the game is launched scaled: a gamescope invocation
whose nested screen equals the wine virtual desktop (640x480), integer-scaled
(x3 -> 1920x1440 on a 2560x1440 output, pillarboxed, pixel-perfect). Both
scripts/create-wine-prefix.py (provisioning) and `rom1 play` (the loop)
write/refresh <target>/play.sh from here, so the flake, the prefix and the
runner cannot drift apart.

The command gamescope supervises is a shell wrapper rather than Wine directly.
Wine leaves prefix services such as winedevice.exe running after the game has
exited; gamescopereaper adopts those processes and otherwise waits for them
forever.  The wrapper stops this dedicated game prefix's wineserver on every
exit path, allowing gamescope to finish normally too.

Import-light on purpose: create-wine-prefix.py imports this standalone,
so nothing from the rom1 package may be pulled in here.
"""

from __future__ import annotations

from pathlib import Path

#: @REPO@ is substituted with the absolute repo root at write time.
_PLAY_SH = """\
#!/usr/bin/env bash
# generated by rom1.graph.play - refreshed by `rom1 play` and
# scripts/create-wine-prefix.py; do not hand-edit.
#
# 640x480 scaled PROPORTIONALLY: gamescope integer scaling, x3 -> 1920x1440,
# pillarboxed on the 2560x1440 output (PLAY_W/PLAY_H override). -w/-h MUST
# equal the prefix's wine virtual desktop (Explorer\\Desktops\\Default), which
# tracks the mode the game actually runs; raise all of them together if a
# larger in-game mode is ever saved.
#
#   ./play.sh                    the rebuilt candidate (game/ALLODS.EXE)
#   ./play.sh ROM1.retail.EXE  the retail control (run it FIRST when
#                                triaging a black screen - retail black-
#                                screening too means the wine env, not the match)
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exe="${1:-ALLODS.EXE}"
echo "[play] $exe md5=$(md5sum "$here/game/$exe" | cut -c1-12)"
game_cmd=(bash -c '
cleanup() {
    wineserver -k >/dev/null 2>&1 || true
}
trap cleanup EXIT
trap "exit 129" HUP
trap "exit 130" INT
trap "exit 143" TERM
wine "$1"
status=$?
exit "$status"
' rom1-play "$exe")
cmd=(env WINEPREFIX="$here/prefix3"
     WINEDLLOVERRIDES="mscoree,mshtml=" WINEDEBUG="${WINEDEBUG:-fixme-all}"
     gamescope -W "${PLAY_W:-2560}" -H "${PLAY_H:-1440}" -w 640 -h 480
     -S integer -F nearest --force-windows-fullscreen -f -- "${game_cmd[@]}")
cd "$here/game"
if command -v gamescope >/dev/null 2>&1; then
    exec "${cmd[@]}"
fi
# outside the play shell: enter it (gamescope + wine); the env prefix above
# outranks its WINEPREFIX shellHook, so a non-default --target still works.
exec nix develop "@REPO@#play" -c "${cmd[@]}"
"""


def write_play_sh(target: Path, repo: Path) -> Path:
    """Write-if-changed <target>/play.sh (0755); returns its path."""
    path = target / "play.sh"
    text = _PLAY_SH.replace("@REPO@", str(repo))
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    path.chmod(0o755)
    return path
